apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: azure-architect-demo
  description: Demo azure architect
  annotations:
    github.com/project-slug: crlsquilumba/azure-architect-demo
spec:
  type: service
  lifecycle: experimental
  owner: user:default/guest
  domain: aplicaciones-internas
  system: Solucion MQ
